import type { Puzzle } from "./types.js";

export const PUZZLE_LIBRARY: Puzzle[] = [
  // --- Easy (3 words, 1 blank) ---
  {
    id: "hotdog-sidekick",
    category: "Classics",
    difficulty: "easy",
    words: ["HOT", "DOG", "TAG", "ALONG", "SIDE", "KICK"],
    timeCapSeconds: 90,
  },
  {
    id: "sun-flower-bed",
    category: "Nature",
    difficulty: "easy",
    words: ["SUN", "FLOWER", "BED", "ROOM"],
    timeCapSeconds: 60,
  },
  {
    id: "note-book-case",
    category: "Everyday",
    difficulty: "easy",
    words: ["NOTE", "BOOK", "CASE"],
    timeCapSeconds: 45,
  },
  {
    id: "base-ball-park",
    category: "Sports",
    difficulty: "easy",
    words: ["BASE", "BALL", "PARK"],
    timeCapSeconds: 45,
  },
  {
    id: "foot-ball-game",
    category: "Sports",
    difficulty: "easy",
    words: ["FOOT", "BALL", "GAME"],
    timeCapSeconds: 45,
  },
  {
    id: "rain-bow-tie",
    category: "Everyday",
    difficulty: "easy",
    words: ["RAIN", "BOW", "TIE"],
    timeCapSeconds: 45,
  },
  {
    id: "snow-ball-room",
    category: "Everyday",
    difficulty: "easy",
    words: ["SNOW", "BALL", "ROOM"],
    timeCapSeconds: 45,
  },
  {
    id: "cup-cake-walk",
    category: "Food",
    difficulty: "easy",
    words: ["CUP", "CAKE", "WALK"],
    timeCapSeconds: 45,
  },
  {
    id: "star-fish-bowl",
    category: "Animals",
    difficulty: "easy",
    words: ["STAR", "FISH", "BOWL"],
    timeCapSeconds: 45,
  },
  {
    id: "arm-chair-man",
    category: "Everyday",
    difficulty: "easy",
    words: ["ARM", "CHAIR", "MAN"],
    timeCapSeconds: 45,
  },
  {
    id: "black-board-walk",
    category: "School",
    difficulty: "easy",
    words: ["BLACK", "BOARD", "WALK"],
    timeCapSeconds: 45,
  },
  {
    id: "back-pack-age",
    category: "Wordplay",
    difficulty: "easy",
    words: ["BACK", "PACK", "AGE"],
    timeCapSeconds: 45,
  },
  {
    id: "ice-cream-cheese",
    category: "Food",
    difficulty: "easy",
    words: ["ICE", "CREAM", "CHEESE"],
    timeCapSeconds: 45,
  },
  {
    id: "high-school-bus",
    category: "Everyday",
    difficulty: "easy",
    words: ["HIGH", "SCHOOL", "BUS"],
    timeCapSeconds: 45,
  },
  {
    id: "peanut-butter-fly",
    category: "Food",
    difficulty: "easy",
    words: ["PEANUT", "BUTTER", "FLY"],
    timeCapSeconds: 45,
  },
  {
    id: "living-room-mate",
    category: "Everyday",
    difficulty: "easy",
    words: ["LIVING", "ROOM", "MATE"],
    timeCapSeconds: 45,
  },

  // --- Medium (4 words, 2 blanks) ---
  {
    id: "basket-ball-room",
    category: "Sports",
    difficulty: "medium",
    words: ["BASKET", "BALL", "ROOM", "MATE"],
    timeCapSeconds: 60,
  },
  {
    id: "fire-fly-weight",
    category: "Nature",
    difficulty: "medium",
    words: ["FIRE", "FLY", "WEIGHT", "LIFTING"],
    timeCapSeconds: 60,
  },
  {
    id: "star-fish-tank",
    category: "Animals",
    difficulty: "medium",
    words: ["STAR", "FISH", "TANK", "TOP"],
    timeCapSeconds: 60,
  },
  {
    id: "tooth-brush-fire-place",
    category: "Everyday",
    difficulty: "medium",
    words: ["TOOTH", "BRUSH", "FIRE", "PLACE"],
    timeCapSeconds: 60,
  },
  {
    id: "sun-flower-pot-hole",
    category: "Nature",
    difficulty: "medium",
    words: ["SUN", "FLOWER", "POT", "HOLE"],
    timeCapSeconds: 60,
  },
  {
    id: "over-board-walk-way",
    category: "Everyday",
    difficulty: "medium",
    words: ["OVER", "BOARD", "WALK", "WAY"],
    timeCapSeconds: 60,
  },
  {
    id: "week-end-game-play",
    category: "Everyday",
    difficulty: "medium",
    words: ["WEEK", "END", "GAME", "PLAY"],
    timeCapSeconds: 60,
  },
  {
    id: "sea-shore-line-up",
    category: "Nature",
    difficulty: "medium",
    words: ["SEA", "SHORE", "LINE", "UP"],
    timeCapSeconds: 60,
  },
  {
    id: "news-paper-work-out",
    category: "Everyday",
    difficulty: "medium",
    words: ["NEWS", "PAPER", "WORK", "OUT"],
    timeCapSeconds: 60,
  },
  {
    id: "play-ground-work-shop",
    category: "School",
    difficulty: "medium",
    words: ["PLAY", "GROUND", "WORK", "SHOP"],
    timeCapSeconds: 60,
  },
  {
    id: "post-office-hour-glass",
    category: "Everyday",
    difficulty: "medium",
    words: ["POST", "OFFICE", "HOUR", "GLASS"],
    timeCapSeconds: 60,
  },

  // --- Hard (4-6 words, 3-4 blanks, less common vocabulary) ---
  {
    id: "moon-light-house-hold",
    category: "Classics",
    difficulty: "hard",
    words: ["MOON", "LIGHT", "HOUSE", "HOLD"],
    timeCapSeconds: 75,
  },
  {
    id: "eye-brow-beat-down",
    category: "Wordplay",
    difficulty: "hard",
    words: ["EYE", "BROW", "BEAT", "DOWN"],
    timeCapSeconds: 60,
  },
  {
    id: "news-stand-point-guard-rail",
    category: "Sports",
    difficulty: "hard",
    words: ["NEWS", "STAND", "POINT", "GUARD", "RAIL"],
    timeCapSeconds: 75,
  },
  {
    id: "over-time-line-up-grade",
    category: "Everyday",
    difficulty: "hard",
    words: ["OVER", "TIME", "LINE", "UP", "GRADE"],
    timeCapSeconds: 75,
  },
  {
    id: "down-town-ship-wreck-age",
    category: "Everyday",
    difficulty: "hard",
    words: ["DOWN", "TOWN", "SHIP", "WRECK", "AGE"],
    timeCapSeconds: 75,
  },
  {
    id: "home-work-out-field-trip-wire",
    category: "School",
    difficulty: "hard",
    words: ["HOME", "WORK", "OUT", "FIELD", "TRIP", "WIRE"],
    timeCapSeconds: 90,
  },
  {
    id: "under-ground-hog-wash-room",
    category: "Wordplay",
    difficulty: "hard",
    words: ["UNDER", "GROUND", "HOG", "WASH", "ROOM"],
    timeCapSeconds: 75,
  },
];
